### ISSUE TITLE
Maybe a little guide for beginners? 

### ISSUE THREAD

**Issue by Imaginev2** [rimuy/weebcord#5]
With this i mean, like a little guide on how it works, how to add a waifu list, where it works and that type of things, i have a doubt right now and it's: Does it works on all servers i am in? . 
sorry if i didn't explain too god but i think you get the idea (?)

**Comment by rimuy** [comment]
Yes it works for all the servers you are in, I sort of forgot to add the waifu list guide, since you just need a .txt file, I thought everyone would get it. I might remake this project later someday with better features and without the need of an extern library, but for now I can make a little guide in README.
